import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Zen Growth palette (motivational + calm)
        surface: "#f5f7f6",
        "surface-dim": "#d7dadb",
        "surface-bright": "#f7fafb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f5",
        "surface-container": "#ebeeef",
        "surface-container-high": "#e6e9ea",
        "surface-container-highest": "#e0e3e4",
        "on-surface": "#1f2937",
        "on-surface-variant": "#475569",
        "inverse-surface": "#2d3132",
        "inverse-on-surface": "#eef1f2",
        outline: "#727973",
        "outline-variant": "#c2c8c2",
        "surface-tint": "#0f766e",
        primary: "#0f766e",
        "on-primary": "#ffffff",
        "primary-container": "#ccfbf1",
        "on-primary-container": "#134e4a",
        "inverse-primary": "#99f6e4",
        secondary: "#14b8a6",
        "on-secondary": "#ffffff",
        "secondary-container": "#99f6e4",
        "on-secondary-container": "#115e59",
        accent: "#f59e0b",
        "on-accent": "#111827",
        tertiary: "#5b5c5c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#747574",
        "on-tertiary-container": "#fdfcfb",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#caead5",
        "primary-fixed-dim": "#aeceba",
        "on-primary-fixed": "#042014",
        "on-primary-fixed-variant": "#314d3d",
        "secondary-fixed": "#dde1ff",
        "secondary-fixed-dim": "#bcc4f1",
        "on-secondary-fixed": "#10193c",
        "on-secondary-fixed-variant": "#3d456a",
        "tertiary-fixed": "#e3e2e1",
        "tertiary-fixed-dim": "#c7c6c5",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#464746",
        background: "#f5f7f6",
        "on-background": "#1f2937",
        "surface-variant": "#e0e3e4"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "element-gap": "24px",
        "card-padding": "32px",
        "container-padding": "40px",
        "section-margin": "64px",
      },
      fontFamily: {
        "headline-xl": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body-lg": ["Manrope", "system-ui", "sans-serif"],
        "body-md": ["Manrope", "system-ui", "sans-serif"],
        "label-md": ["Manrope", "system-ui", "sans-serif"],
        "label-sm": ["Manrope", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-xl": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.02em", fontWeight: "700" },
        ],
      },
      boxShadow: {
        soft: "0 10px 40px rgba(118, 148, 130, 0.08)",
      },
    },
  },
  plugins: [],
} satisfies Config;

